### PR TITLE
Fix crash on second notification + pie chart. Complete french translation. Add compat 3.26, 3.24, 3.22. Add sound notification with loop and panel settings

### PR DESCRIPTION
**Pull request by takuyozora**
Many improvements : 
- No more crash of gnnome-shell on the second notification : 
  - https://github.com/olebowle/gnome-shell-timer/issues/27
- Pie chart visible again and no more warning message : 
  - https://github.com/olebowle/gnome-shell-timer/issues/31
- Complete french translation, included settings dialog
- Add compatibility for gnome-shell 3.26, 3.24 and 3.22
- Merge pull request : https://github.com/olebowle/gnome-shell-timer/pull/34 and add loop and panel in settings for sound

### CODE REVIEW

**Comment by blackjackshellac** [comment]
@takuyozora There should be a way to stop the looping sound notification, without a persistent notification or that option should be forced when enabling looping sound.  What do you think?

**Comment by blackjackshellac** [comment]
@takuyozora I've created a diff that will clear and recreate the PanelMenu after a settings change. I'm not sure if this is the best way to do it but it seems to work. The main changes are the addition of _createMenu() and the call to menu.removeAll().  Most of the other diffs have to do with whitespace since it had a mix of spaces and tabs for indenting.  If you want I guess I could fork your fork and create a pull request from there since @olebowle doesn't seem to be responding to pull requests.

```
diff --git a/timer@olebowle.gmx.com/extension.js b/timer@olebowle.gmx.com/extension.js
index 901284f..a1feb58 100644
--- a/timer@olebowle.gmx.com/extension.js
+++ b/timer@olebowle.gmx.com/extension.js
@@ -31,7 +31,7 @@ const MessageTray = imports.ui.messageTray;
 const ModalDialog = imports.ui.modalDialog;
 const PanelMenu = imports.ui.panelMenu;
 const PopupMenu = imports.ui.popupMenu;
-const Slider = imports.ui.slider; 
+const Slider = imports.ui.slider;
 
 const Gettext = imports.gettext.domain('gnome-shell-timer');
 const Util = imports.misc.util;
@@ -60,6 +60,7 @@ Indicator.prototype = {
         this._settings = getSettings('org.gnome.shell.extensions.timer');
 
         let load_time = Lang.bind(this, function() {
+            log("load time");
             this._hours = this._settings.get_int('manual-hours');
             this._minutes = this._settings.get_int('manual-minutes');
             this._seconds = this._settings.get_int('manual-seconds');
@@ -67,6 +68,7 @@ Indicator.prototype = {
         });
 
         let load_settings = Lang.bind(this, function() {
+            log("load settings");
             this._showNotifications = this._settings.get_boolean('ui-notification');
             this._showPersistentNotifications = this._settings.get_boolean('ui-persistent');
             this._showElapsed = this._settings.get_boolean('ui-elapsed');
@@ -75,9 +77,11 @@ Indicator.prototype = {
             this._darkColor = this._settings.get_string('ui-dark-color');
             this._lightColor = this._settings.get_string('ui-light-color');
             this._presets = this._settings.get_value('presets').deep_unpack();
-			      this._soundUri = this._settings.get_string('sound-uri');
-			      this._sound_enable = this._settings.get_boolean('sound-enable');
-			      this._sound_loop = this._settings.get_boolean('sound-loop');
+            this._soundUri = this._settings.get_string('sound-uri');
+            this._sound_enable = this._settings.get_boolean('sound-enable');
+            this._sound_loop = this._settings.get_boolean('sound-loop');
+
+            this._createMenu();
         });
 
         // Watch settings for changes
@@ -92,9 +96,9 @@ Indicator.prototype = {
         this._settings.connect('changed::ui-dark-color', load_settings);
         this._settings.connect('changed::ui-light-color', load_settings);
         this._settings.connect('changed::presets', load_settings);
-		    this._settings.connect('changed::sound-uri', load_settings);
-		    this._settings.connect('changed::sound-enable', load_settings);
-		    this._settings.connect('changed::sound-loop', load_settings);
+        this._settings.connect('changed::sound-uri', load_settings);
+        this._settings.connect('changed::sound-enable', load_settings);
+        this._settings.connect('changed::sound-loop', load_settings);
 
         //Set Box
         this._box = new St.BoxLayout({ name: 'panelStatusMenu' });
@@ -116,9 +120,17 @@ Indicator.prototype = {
 
         //Set Logo
         this._logo = new St.Icon({ icon_name: 'utilities-timer-symbolic',
-                                 style_class: 'system-status-icon'});
+            style_class: 'system-status-icon'});
         this.actor.add_actor(this._logo);
 
+        this._createMenu();
+
+        //Start the timer
+        this._refreshTimer();
+    },
+
+    _createMenu: function() {
+        this.menu.removeAll();
         //Toggle timer state button
         this._widget = new PopupMenu.PopupSwitchMenuItem(_("Run Timer"), false);
         this._widget.connect("toggled", Lang.bind(this, function() {
@@ -146,22 +158,22 @@ Indicator.prototype = {
         this.menu.addMenuItem(new PopupMenu.PopupSeparatorMenuItem());
 
         for (let ke in this._presets) {
-        //introduce a new variable see:
-        //https://mail.gnome.org/archives/gnome-shell-list/2011-August/msg00105.html
-                let key = ke;
-                let item = new PopupMenu.PopupMenuItem(_(key));
-                let label = new St.Label();
-                this._formatLabel(label, this._presets[key]);
-                let bin = new St.Bin({ x_align: St.Align.END });
-                bin.child = label;
-
-                item.actor.add(bin, { expand: true, x_align: St.Align.END });
-                item.connect('activate', Lang.bind(this, function() {
-                    this._time = this._presets[key];
-                    this._issuer = key;
-                    this._restartTimer();
-                }));
-                this.menu.addMenuItem(item);
+            //introduce a new variable see:
+            //https://mail.gnome.org/archives/gnome-shell-list/2011-August/msg00105.html
+            let key = ke;
+            let item = new PopupMenu.PopupMenuItem(_(key));
+            let label = new St.Label();
+            this._formatLabel(label, this._presets[key]);
+            let bin = new St.Bin({ x_align: St.Align.END });
+            bin.child = label;
+
+            item.actor.add(bin, { expand: true, x_align: St.Align.END });
+            item.connect('activate', Lang.bind(this, function() {
+                this._time = this._presets[key];
+                this._issuer = key;
+                this._restartTimer();
+            }));
+            this.menu.addMenuItem(item);
         }
 
         //Separator only if there are presets
@@ -180,9 +192,6 @@ Indicator.prototype = {
             Util.spawn(['gnome-shell-timer-config']);
         });
         this.menu.addMenuItem(item);
-
-        //Start the timer
-        this._refreshTimer();
     },
 
     //Add sliders SubMenu to manually set the timer
@@ -196,7 +205,7 @@ Indicator.prototype = {
         this._timerMenu.menu.addMenuItem(item);
 
         item = new PopupMenu.PopupBaseMenuItem({ activate: false });
-        this._hoursSlider = new Slider.Slider(0); 
+        this._hoursSlider = new Slider.Slider(0);
         this._hoursSlider._value = this._hours / 23;
         this._hoursSlider.connect('value-changed', Lang.bind(this, function() {
             this._hours = Math.ceil(this._hoursSlider._value*23);
@@ -204,7 +213,7 @@ Indicator.prototype = {
             this._time = this._hours*3600 + this._minutes*60 + this._seconds;
             this._issuer = 'setTimer';
         } ));
-        item.actor.add(this._hoursSlider.actor, { expand: true }); 
+        item.actor.add(this._hoursSlider.actor, { expand: true });
         this._timerMenu.menu.addMenuItem(item);
 
         //Minutes
@@ -216,7 +225,7 @@ Indicator.prototype = {
         this._timerMenu.menu.addMenuItem(item);
 
         item = new PopupMenu.PopupBaseMenuItem({ activate: false });
-        this._minutesSlider = new Slider.Slider(0); 
+        this._minutesSlider = new Slider.Slider(0);
         this._minutesSlider._value = this._minutes / 59;
         this._minutesSlider.connect('value-changed', Lang.bind(this, function() {
             this._minutes = Math.ceil(this._minutesSlider._value*59);
@@ -224,7 +233,7 @@ Indicator.prototype = {
             this._time = this._hours*3600 + this._minutes*60 + this._seconds;
             this._issuer = 'setTimer';
         } ));
-        item.actor.add(this._minutesSlider.actor, { expand: true }); 
+        item.actor.add(this._minutesSlider.actor, { expand: true });
         this._timerMenu.menu.addMenuItem(item);
 
         //Seconds
@@ -236,7 +245,7 @@ Indicator.prototype = {
         this._timerMenu.menu.addMenuItem(item);
 
         item = new PopupMenu.PopupBaseMenuItem({ activate: false });
-        this._secondsSlider = new Slider.Slider(0); 
+        this._secondsSlider = new Slider.Slider(0);
         this._secondsSlider._value = this._seconds / 59;
         this._secondsSlider.connect('value-changed', Lang.bind(this, function() {
             this._seconds = Math.ceil(this._secondsSlider._value*59);
@@ -244,7 +253,7 @@ Indicator.prototype = {
             this._time = this._hours*3600 + this._minutes*60 + this._seconds;
             this._issuer = 'setTimer';
         } ));
-        item.actor.add(this._secondsSlider.actor, { expand: true }); 
+        item.actor.add(this._secondsSlider.actor, { expand: true });
         this._timerMenu.menu.addMenuItem(item);
     },
 
@@ -278,7 +287,7 @@ Indicator.prototype = {
         Clutter.cairo_set_source_color(cr, background);
         cr.rectangle(0, 0, width, height);
         cr.fill();*/
-        arc(8,this._timeSpent,this._time,-pi/2, this._lightColor, this._darkColor);        
+        arc(8,this._timeSpent,this._time,-pi/2, this._lightColor, this._darkColor);
     },
 
     //Reset all counters and timers
@@ -312,8 +321,8 @@ Indicator.prototype = {
         if(this._timeSpent && this._time <= this._timeSpent) {
             this._resetTimer();
 
-			//this._notifyUser(this._soundUri);
-			this._playSound(this._soundUri);
+            //this._notifyUser(this._soundUri);
+            this._playSound(this._soundUri);
 
             if(this._issuer == 'setTimer')
                 this._notifyUser(_("Timer finished!"));
@@ -350,53 +359,53 @@ Indicator.prototype = {
             source.notify(notification);
         }
         if(this._showPersistentNotifications) {
-        	//Create persistent message modal dialog
- 	    this._persistentMessageDialog = new ModalDialog.ModalDialog();
-	    this._persistentMessageLabel = new St.Label({ style_class: 'persistent-message-label',
-        	text: _(text) });
-	    this._persistentMessageDialog.contentLayout.add(this._persistentMessageLabel, { x_fill: true, y_fill: true });
-       	    this._persistentMessageDialog.setButtons([{ label: _("Close"),
-	        action: Lang.bind(this, function(param) { 
-	          this._persistentMessageDialog.close(); 
-	          if(this._sound_enable){
-	            this.player.set_state(Gst.State.NULL); 
-	          }
-	        }),
-	        key:    Clutter.Escape
-	    }]);
+            //Create persistent message modal dialog
+            this._persistentMessageDialog = new ModalDialog.ModalDialog();
+            this._persistentMessageLabel = new St.Label({ style_class: 'persistent-message-label',
+                text: _(text) });
+            this._persistentMessageDialog.contentLayout.add(this._persistentMessageLabel, { x_fill: true, y_fill: true });
+            this._persistentMessageDialog.setButtons([{ label: _("Close"),
+                action: Lang.bind(this, function(param) {
+                    this._persistentMessageDialog.close();
+                    if(this._sound_enable){
+                        this.player.set_state(Gst.State.NULL);
+                    }
+                }),
+                key:    Clutter.Escape
+            }]);
             this._persistentMessageDialog.open();
         }
     },
 
-	// szm - from tea-time
-	_playSound: function(uri) {
-	  if (this._sound_enable) {
-		  if ( typeof this.player == 'undefined' ) {
-			  Gst.init(null, 0);
-			  this.player  = Gst.ElementFactory.make("playbin","player");
-			  this.playBus = this.player.get_bus();
-			  this.playBus.add_signal_watch();
-			  this.playBus.connect("message", Lang.bind(this,
-				  function(playBus, message) {
-					  if (message != null) {
-						  // IMPORTANT: to reuse the player, set state to READY
-						  let t = message.type;
-						  if ( t == Gst.MessageType.EOS || t == Gst.MessageType.ERROR) {
-							  this.player.set_state(Gst.State.READY);
-						  }
-						  if ( t == Gst.MessageType.EOS && this._sound_loop ){
-						    this.player.set_state(Gst.State.READY);
-						    this.player.set_property('uri', uri);
-           		  this.player.set_state(Gst.State.PLAYING);
-						  }
-					  } // message handler
-				  }));
-		  } // if undefined
-		  //this._notifyUser("Playing uri="+uri);
-		  this.player.set_property('uri', uri);
-		  this.player.set_state(Gst.State.PLAYING);
-		}
-	}
+    // szm - from tea-time
+    _playSound: function(uri) {
+        if (this._sound_enable) {
+            if ( typeof this.player == 'undefined' ) {
+                Gst.init(null, 0);
+                this.player  = Gst.ElementFactory.make("playbin","player");
+                this.playBus = this.player.get_bus();
+                this.playBus.add_signal_watch();
+                this.playBus.connect("message", Lang.bind(this,
+                    function(playBus, message) {
+                        if (message != null) {
+                            // IMPORTANT: to reuse the player, set state to READY
+                            let t = message.type;
+                            if ( t == Gst.MessageType.EOS || t == Gst.MessageType.ERROR) {
+                                this.player.set_state(Gst.State.READY);
+                            }
+                            if ( t == Gst.MessageType.EOS && this._sound_loop ){
+                                this.player.set_state(Gst.State.READY);
+                                this.player.set_property('uri', uri);
+                                this.player.set_state(Gst.State.PLAYING);
+                            }
+                        } // message handler
+                    }));
+            } // if undefined
+            //this._notifyUser("Playing uri="+uri);
+            this.player.set_property('uri', uri);
+            this.player.set_state(Gst.State.PLAYING);
+        }
+    }
 
 };
 


```

**Comment by olebowle** [comment]
@blackjackshellac I'm quite busy these days. I'll try to incorporate all the PRs in 3-4 weeks. Until then I won't have great internet access. We can also think about giving other developers commit rights, as I'm not using this extension anymore.

**Comment by blackjackshellac** [comment]
I assumed you were busy with other projects.  I can wait a few weeks.  Maybe when you're ready you can consider giving commit rights to myself and @takuyozora if they are also interested.  I'd like to see this extension added to extensions.gnome.org eventually.

**Comment by olebowle** [comment]
Can you please rebase your PR? I didn't see that you merged your other PR in this one. Furthermore, there are now merge conflicts.

**Comment by rhertzog** [comment]
What's the status here? Can this be merged? I would like to see 3.26 support in master.

**Comment by takuyozora** [comment]
My current 'master' branch is running on my laptop without any problem. 
So I think it's ready for a merge.

**Comment by olebowle** [comment]
Thanks for the PR. Sorry for the delay!

**Pull request merged**
